### ISSUE TITLE
Original Data

### ISSUE THREAD

**Issue by LLM4Rec** [chenyuxin1999/S-DPO#2]
Hello, could you provide the original dataset and processing scripts? Without your dataset, it would be difficult to understand the step-by-step process from raw data to the data warehouse. Could you please provide it? Thank you.
e.g., I don't know how to get the final processed data from the public dataset.

**Comment by LLM4Rec** [comment]
I don't understand why it's necessary to include text such as "[HistoryEmb]", "[CansEmb]", "[PH]" in the data?

**Comment by chenyuxin1999** [comment]
Hi @LLM4Rec,

Thank you for your interest in our work.

Regarding your first question, I will organize and update the data processing scripts in the next few days. The original dataset is not directly hosted in the GitHub repository due to size limitations, but it can be easily downloaded from the official website.

As for your second question, my prompt does not include the identifiers "[HistoryEmb]", "[CansEmb]", or "[PH]". Could you please confirm if this issue is being raised in the correct repository? The relevant identifiers in my prompt are "[HistoryHere]" and "[CansHere]", which serve as placeholders that will be further replaced by history interactions and candidate sets. You can refer to this in the code here: https://github.com/chenyuxin1999/S-DPO/blob/1e7d5ccb413191ccea565283f17ff9702f827d60/Prompt.py#L24 .

**Comment by LLM4Rec** [comment]
https://github.com/chenyuxin1999/S-DPO/blob/1e7d5ccb413191ccea565283f17ff9702f827d60/data/data_interface.py#L40-L61

Look here, why is there text like "[HistoryEmb]", "[CansEmb]", "[PH]"?

**Comment by chenyuxin1999** [comment]
Sorry for causing confusion. This part of the code is unused in our project. We appreciate you pointing it out. We will reorganize our repo and release a new version in a few days.

**Comment by chenyuxin1999** [comment]
Hi, we have reorganized our code and removed the unused parts. If you have any other questions, please feel free to let us know.

**Comment by LLM4Rec** [comment]
@chenyuxin1999 Hello, When will you share the complete data processing script? Thanks!
